### ISSUE TITLE
Rotate logs by default

### ISSUE THREAD

**Issue by retlehs** [roots/bedrock-ansible#141]
(not sure if this would apply to all logs, but created this issue after looking at a pretty big nginx access log)

**Comment by fullyint** [comment]
I'm new to it all, but this seems to rotate logs in `/srv/www/example.com/logs`. 

Add to `roles/wordpress-sites/tasks/nginx.yml`, after "Create WordPress configuration for Nginx": 
```yaml
- name: Enable logrotate for WordPress logs
  template: src="logrotate.j2"
            dest="/etc/logrotate.d/nginx-wordpress"
  with_items: wordpress_sites
```
Does it need a `notify: reload nginx`?

And a new template `roles/wordpress-sites/templates/logrotate.j2`:
```
{{ www_root }}/{{ item.site_name }}/logs/*.log {
        weekly
        missingok
        rotate 52
        compress
        delaycompress
        notifempty
        create 0640 {{ item.user | default(user) }} www-data
        sharedscripts
        prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi \
        endscript
        postrotate
                invoke-rc.d nginx rotate >/dev/null 2>&1
        endscript
}
```
