### ISSUE TITLE
Error in wordpress-install task: This does not seem to be a WordPress install.

### ISSUE THREAD

**Issue by workerdem** [roots/bedrock-ansible#161]
Hi everyone. This is the first time I am using bedrock-ansible. I did everything described in [installation section](https://github.com/roots/bedrock-ansible#installation). However, I got this weird error:

```
TASK: [wordpress-install | WP installed?] *************************************
failed: [default] => (item={'key': 'example.dev', 'value': {'site_install': True, 'multisite': {'enabled': False}, 'local_path': '../example.com', 'admin_user': 'admin', 'site_title': 'Example Site', 'admin_password': 'admin', 'env': {'db_name': 'example_dev', 'wp_env': 'development', 'db_user': 'example_dbuser', 'db_password': 'example_dbpassword', 'wp_home': 'http://example.dev', 'wp_siteurl': 'http://example.dev/wp'}, 'site_hosts': ['example.dev'], 'system_cron': True, 'admin_email': 'admin@example.dev'}}) => {"changed": true, "cmd": ["wp", "core", "is-installed", "--allow-root"], "delta": "0:00:00.073077", "end": "2015-04-06 07:09:05.568034", "item": {"key": "example.dev", "value": {"admin_email": "admin@example.dev", "admin_password": "admin", "admin_user": "admin", "env": {"db_name": "example_dev", "db_password": "example_dbpassword", "db_user": "example_dbuser", "wp_env": "development", "wp_home": "http://example.dev", "wp_siteurl": "http://example.dev/wp"}, "local_path": "../example.com", "multisite": {"enabled": false}, "site_hosts": ["example.dev"], "site_install": true, "site_title": "Example Site", "system_cron": true}}, "rc": 1, "start": "2015-04-06 07:09:05.494957", "warnings": []}
stderr: Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
...ignoring

TASK: [wordpress-install | Install WP] ****************************************
failed: [default] => (item={u'cmd': [u'wp', u'core', u'is-installed', u'--allow-root'], u'end': u'2015-04-06 07:09:05.568034', u'stderr': u'Error: This does not seem to be a WordPress install.\nPass --path=`path/to/wordpress` or run `wp core download`.', u'stdout': u'', u'changed': True, u'rc': 1, 'item': {'value': {'site_install': True, 'multisite': {'enabled': False}, 'admin_user': 'admin', 'system_cron': True, 'local_path': '../example.com', 'site_title': 'Example Site', 'admin_password': 'admin', 'env': {'db_name': 'example_dev', 'wp_env': 'development', 'db_user': 'example_dbuser', 'db_password': 'example_dbpassword', 'wp_home': 'http://example.dev', 'wp_siteurl': 'http://example.dev/wp'}, 'site_hosts': ['example.dev'], 'admin_email': 'admin@example.dev'}, 'key': 'example.dev'}, u'warnings': [], u'delta': u'0:00:00.073077', 'invocation': {'module_name': u'command', 'module_args': u'wp core is-installed --allow-root'}, 'stdout_lines': [], u'start': u'2015-04-06 07:09:05.494957'}) => {"changed": true, "cmd": ["wp", "core", "install", "--allow-root", "--url=http://example.dev", "--title=Example Site", "--admin_user=admin", "--admin_password=admin", "--admin_email=admin@example.dev"], "delta": "0:00:00.045020", "end": "2015-04-06 07:09:05.834203", "item": {"changed": true, "cmd": ["wp", "core", "is-installed", "--allow-root"], "delta": "0:00:00.073077", "end": "2015-04-06 07:09:05.568034", "invocation": {"module_args": "wp core is-installed --allow-root", "module_name": "command"}, "item": {"key": "example.dev", "value": {"admin_email": "admin@example.dev", "admin_password": "admin", "admin_user": "admin", "env": {"db_name": "example_dev", "db_password": "example_dbpassword", "db_user": "example_dbuser", "wp_env": "development", "wp_home": "http://example.dev", "wp_siteurl": "http://example.dev/wp"}, "local_path": "../example.com", "multisite": {"enabled": false}, "site_hosts": ["example.dev"], "site_install": true, "site_title": "Example Site", "system_cron": true}}, "rc": 1, "start": "2015-04-06 07:09:05.494957", "stderr": "Error: This does not seem to be a WordPress install.\nPass --path=`path/to/wordpress` or run `wp core download`.", "stdout": "", "stdout_lines": [], "warnings": []}, "rc": 1, "start": "2015-04-06 07:09:05.789183", "warnings": []}
stderr: Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/workerdem/dev.retry

default                    : ok=65   changed=35   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Did I miss something?

**Comment by fullyint** [comment]
I think the problem could be the discrepancy between `example.com` vs `example.dev`. I think you've named your bedrock directory `example.com`, but your `group_vars/development` probably has this...
```yaml
wordpress_sites:
  example.dev:
    site_hosts:
      - example.dev
    local_path: '../example.com' 
```

Things might work if you change the two instances of `example.dev` above to `example.com`. Or, switch the name of your bedrock directory to `example.dev` and also switch the value for `local_path` above. Assuming that was the problem, I see that a recent rewrite of the README leads you right into this naming discrepancy. Let us know if that fixes it.

**Comment by workerdem** [comment]
@fullyint You are right about my configuration. I changed all example.dev instances to example.com and got the following configuration:

```yaml
mysql_root_password: devpw

web_user: vagrant

wordpress_sites:
  example.com:
    site_hosts:
      - example.com
    local_path: '../example.com' # path targeting local project directory (relative to root/Vagrantfile)
    site_install: true
    site_title: Example Site
    admin_user: admin
    admin_password: admin
    admin_email: admin@example.com
    system_cron: true
    multisite:
      enabled: false
    env:
      wp_home: http://example.com
      wp_siteurl: http://example.com/wp
      wp_env: development
      db_name: example_dev
      db_user: example_dbuser
      db_password: example_dbpassword

php_error_reporting: 'E_ALL'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_track_errors: 'On'
php_mysqlnd_collect_memory_statistics: 'On'
php_opcache_enable: 0
```

However, I still get the same error. I also renamed bedrock directory `example.com` to `example.dev` and changed `local_path` accordingly, but still get the same error.
