### ISSUE TITLE
Re-running ansible-playbook fails on Set root user password

### ISSUE THREAD

**Issue by merchantguru** [roots/bedrock-ansible#191]
Running `ansible-playbook -i hosts/production server.yml` a second time leads to:

```bash
TASK: [mariadb | Set root user password] ************************************** 
failed: [104.xxx.xxx.xx] => (item=Raven) => {"failed": true, "item": "Raven"}
msg: (1396, "Operation CREATE USER failed for 'root'@'raven'")
ok: [104.xxx.xxx.xx] => (item=127.0.0.1)
ok: [104.xxx.xxx.xx] => (item=::1)
ok: [104.xxx.xxx.xx] => (item=localhost)

FATAL: all hosts have already failed -- aborting
```

I need to delete the root@Raven user in MariaDB in order to proceed. Is there a way to skip this user creation on subsequent runs?

**Comment by austinpray** [comment]
For debugging: what is your server setup?

**Comment by merchantguru** [comment]
Stock Digital Ocean Ubuntu 14.04 x64 vmlinuz-3.13.0-43-generic 512mb. Everything else I left to bedrock-ansible.

**Comment by Foxaii** [comment]
I've not been able to replicate this.  Can you let us know what version of Ansible you are using?

**Comment by merchantguru** [comment]
ansible 1.9.0.1
  configured module search path = None

**Comment by retlehs** [comment]
i was able to reproduce this when trying to provision a DO server as well

**Comment by merchantguru** [comment]
So, my suggestion is to replace

```yaml
- name: Set root user password
  mysql_user: name=root
              ...
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
```

with

```yaml
- name: Set root user password
  mysql_user: name=root
              ...
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
```

**Comment by swalkinshaw** [comment]
I'd be fine with that change but I'm curious why it fixes the issue. Also skeptical it really fixes the underlying bug across different use cases (hosts/inventory/hostnames etc).

Although it seems like `ansible_hostname` is a little strange and not documented well: https://github.com/ansible/ansible/issues/9971

So maybe we should just change this anyway and hopefully it also fixes this issue for everyone.

**Comment by merchantguru** [comment]
There are 2 tasks for removing anonymous users. We could convert those to one task and include the `inventory_hostname` for good measure. 

Replace:

```yaml
- name: Delete anonymous MySQL server user for current hostname
  mysql_user: user=""
              host="{{ ansible_hostname }}"
              state=absent
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"

- name: Delete anonymous MySQL server user for localhost
  mysql_user: user=""
              state=absent
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
```

with

```yaml
- name: Delete anonymous users from the database
  mysql_user: user=""
              host="{{ item }}"
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
              state=absent
  with_items:
    - localhost
    - {{ inventory_hostname }}
    - {{ ansible_hostname }}
```
